### ISSUE TITLE
Show List app when click this tab

### ISSUE THREAD

**Issue by kurodenjiro** [drop-wallet-tg/telegram-bot-v2#11]
![image](https://github.com/drop-wallet-tg/telegram-bot-v2/assets/26534614/48b55b78-13d0-451e-b44a-2738df49bc0d)
Show bluntDao , Nearsocial app , NFTs

**Comment by louisdevzz** [comment]
Tab do ko hien NFT nua ha anh can them 1 tab moi de hien NFT dung ko anh @kurodenjiro

**Comment by kurodenjiro** [comment]
![image](https://github.com/drop-wallet-tg/telegram-bot-v2/assets/26534614/4b43ef16-ac8f-471a-ad18-28631387239f)
![image](https://github.com/drop-wallet-tg/telegram-bot-v2/assets/26534614/9c18c506-fa19-469c-881d-aee5ceef77d3)
@louisdevzz  When you click on apps, you will use the app directly like clicking on the app in the list below
