### ISSUE TITLE
Long Name Wallet

### ISSUE THREAD

**Issue by kurodenjiro** [drop-wallet-tg/telegram-bot-v2#2]
When I import wallet larger than 32 characters, it overflows and covers the screen. Need to reduce characters when wallet is larger than 10 characters, for example abc....323.near
![image](https://github.com/drop-wallet-tg/telegram-bot-v2/assets/26534614/7d358077-2b0f-46c3-874f-b1bec681c91b)

**Comment by louisdevzz** [comment]
Done
