### ISSUE TITLE
Display error message

### ISSUE THREAD

**Issue by kurodenjiro** [drop-wallet-tg/telegram-bot-v2#5]
![image](https://github.com/drop-wallet-tg/telegram-bot-v2/assets/26534614/4f7678e3-20b1-482a-9df1-430748fee14b)
There is no need to display error messages like this. Just disable the button when the user has not entered a character. Only displayed if that wallet does not exist. and shows right below accountIDinstead of showing at the top

**Comment by louisdevzz** [comment]
Done
