### ISSUE TITLE
Do not display copied when clicking copy

### ISSUE THREAD

**Issue by kurodenjiro** [drop-wallet-tg/telegram-bot-v2#6]
display a notification in the center of the screen is copied !

**Comment by louisdevzz** [comment]
Nay em da fix roi ma em lo push thang vao main roi anh @kurodenjiro 
https://github.com/drop-wallet-tg/telegram-bot-v2/commit/17d8bd4c921f840875e4a815125bd240f4703d70

**Comment by kurodenjiro** [comment]
![image](https://github.com/drop-wallet-tg/telegram-bot-v2/assets/26534614/80d7c8af-299f-4877-a9c5-5011dfc24034)
need to change the color to match the color of the dropwallet
